name: example
flag_format: example{%s}
challenges:
  cmgr/examples/custom-socat:
    seeds: [ 1, 5, 101 ]
    instance_count: 1
  cmgr/examples/aptitude-and-privileges:
    seeds: [ 19, 42, 15412 ]
    instance_count: -1
